project: PROJECT_NAME
version: PROJECT_VERSION

database:
  host: DATABASE_HOST:DATABASE_PORT
  dbname: DATABASE_NAME
  user: DATABASE_USERNAME
  password: DATABASE_PASSWORD

mail:
  host: MAIL_HOST
  user: MAIL_USERNAME
  password: MAIL_PASSWORD

regex:
  alphanum: '[\w\s\-]+'
  string: '.'
  stringAcc: '[\p{L}\p{Nd}\s-_]+'
  int: '\d+'
  email: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}'
  boolean: '(true|false)'
  booleanInt: '(1|0)'
  frenchDate: '(0?[1-9]|[12][0-9]|3[01])\/(0?[1-9]|1[0-2])\/\d{4}'
  usDate: '\d{4}\-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01])'
  datetime: '\d{4}-(0?[1-9]|1[0-2])-(0?[1-9]|[12][0-9]|3[01]) (00|[0-9]|1[0-9]|2[0-3]):([0-9]|[0-5][0-9])(:([0-9]|[0-5][0-9]))?'

token:
  expire: TOKEN_EXPIRE # 7 days in seconds (set NULL if you want no expiration token)

docTags:
  name: DescriptionTag
  token: FlagTag
  codes: ArrayTag
  render: DescriptionTag
  table: DescriptionTag

path:
  foo: bar
